environment:
  nodejs_version: "8.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i flow-typed -g
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
